language: python
jobs:
  include:
    - python: "3.8"
      env: TOXENV=black,flake8
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.7"
      env: TOXENV=py37
install:
  - pip install tox
script:
  - tox
