language: python
jobs:
  include:
    - python: "3.9"
      env: TOXENV=py39
      # as soon as black > 20.8b1 is released, we start using it and this bug is
      # fixed: https://bugs.python.org/issue43498, we can move these tests to the python 3.9 job
    - python: "3.8"
      env: TOXENV=black,flake8
    - python: "3.8"
      env: TOXENV=py38
install:
  - pip install tox
script:
  - tox
