version: '3'
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: cachito
      POSTGRES_PASSWORD: cachito
      POSTGRES_DB: cachito
      POSTGRES_INITDB_ARGS: "--auth='ident' --auth='trust'"

  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: cachito
      RABBITMQ_DEFAULT_PASS: cachito
    ports:
      # The RabbitMQ management console
      - 8081:15672

  cachito-api:
    build: .
    command:
    - /bin/sh
    - -c
    - >-
      pip3 uninstall -y cachito &&
      python3 setup.py develop --no-deps &&
      cachito wait-for-db &&
      cachito db upgrade &&
      flask-3 run --reload --host 0.0.0.0 --port 8080
    environment:
      FLASK_ENV: development
      FLASK_APP: cachito/web/wsgi.py
    volumes:
      - ./:/src:z
    depends_on:
      - db
    ports:
      - 8080:8080

  # TODO: Figure out auto-reloading of Celery workers during development
  cachito-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-workers
    environment:
      CACHITO_DEV: 'true'
    volumes:
      - ./:/src:z
    depends_on:
      - cachito-api
      - rabbitmq
