version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: cachito
      POSTGRES_PASSWORD: cachito
      POSTGRES_DB: cachito
      POSTGRES_INITDB_ARGS: "--auth='ident' --auth='trust'"

  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: cachito
      RABBITMQ_DEFAULT_PASS: cachito
    ports:
      # The RabbitMQ management console
      - 8081:15672

  athens:
    image: gomods/athens:v0.7.0
    environment:
      ATHENS_DISK_STORAGE_ROOT: /var/lib/athens
      ATHENS_STORAGE_TYPE: disk
    volumes:
      - ./tmp/athens-storage:/var/lib/athens:z
    ports:
      - 3000:3000

  cachito-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api
    command:
    - /bin/sh
    - -c
    - >-
      pip3 uninstall -y cachito &&
      python3 setup.py develop --no-deps &&
      cachito wait-for-db &&
      cachito db upgrade &&
      flask-3 run --reload --host 0.0.0.0 --port 8080
    environment:
      FLASK_ENV: development
      FLASK_APP: cachito/web/wsgi.py
      CACHITO_DEV: 'true'
    volumes:
      - ./:/src:z
      - ./tmp/cachito-archives:/tmp/cachito-archives:z
    # This is needed in order to allow cleaning up a temporary tarball
    # which is populated by the worker container. In an OpenShift environment
    # this is not needed.
    privileged: true
    depends_on:
      - db
    ports:
      - 8080:8080

  cachito-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-workers
    # Override the default command so that Celery auto-reloads on code changes
    command:
    - /bin/bash
    - -c
    - >-
      pip3 install watchdog[watchmedo] &&
      watchmedo auto-restart -d ./cachito/workers -p '*.py' --recursive \
        -- /bin/celery-3 -A cachito.workers.tasks worker --loglevel=info
    environment:
      CACHITO_DEV: 'true'
    volumes:
      - ./:/src:z
      - ./tmp/cachito-archives:/tmp/cachito-archives:z
    depends_on:
      - cachito-api
      - rabbitmq
