"""Remove Package, RequestPackage, and RequestDependency tables

Revision ID: 51ab214ff52f
Revises: 418241dba06c
Create Date: 2022-07-15 13:23:27.320529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ab214ff52f'
down_revision = '418241dba06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_dependency', schema=None) as batch_op:
        batch_op.drop_index('ix_request_dependency_dependency_id')
        batch_op.drop_index('ix_request_dependency_package_id')
        batch_op.drop_index('ix_request_dependency_replaced_dependency_id')
        batch_op.drop_index('ix_request_dependency_request_id')

    op.drop_table('request_dependency')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index('ix_package_dev')
        batch_op.drop_index('ix_package_name')
        batch_op.drop_index('ix_package_type')
        batch_op.drop_index('ix_package_version')

    op.drop_table('package')
    with op.batch_alter_table('request_package', schema=None) as batch_op:
        batch_op.drop_index('ix_request_package_package_id')
        batch_op.drop_index('ix_request_package_request_id')

    op.drop_table('request_package')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_package',
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.Column('package_id', sa.INTEGER(), nullable=False),
    sa.Column('subpath', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'package_id'),
    sa.UniqueConstraint('request_id', 'package_id')
    )
    with op.batch_alter_table('request_package', schema=None) as batch_op:
        batch_op.create_index('ix_request_package_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_request_package_package_id', ['package_id'], unique=False)

    op.create_table('package',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.VARCHAR(), nullable=False),
    sa.Column('dev', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dev', 'name', 'type', 'version', name='dependency_dev_name_type_version_key')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index('ix_package_version', ['version'], unique=False)
        batch_op.create_index('ix_package_type', ['type'], unique=False)
        batch_op.create_index('ix_package_name', ['name'], unique=False)
        batch_op.create_index('ix_package_dev', ['dev'], unique=False)

    op.create_table('request_dependency',
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.Column('dependency_id', sa.INTEGER(), nullable=False),
    sa.Column('replaced_dependency_id', sa.INTEGER(), nullable=True),
    sa.Column('package_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['package.id'], name='request_dependency_dependency_id_fkey'),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name='fk_request_dependency_package_id'),
    sa.ForeignKeyConstraint(['replaced_dependency_id'], ['package.id'], name='fk_replaced_dependency_id'),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name='request_dependency_request_id_fkey'),
    sa.UniqueConstraint('request_id', 'dependency_id', 'package_id', name='request_dependency_request_id_dependency_id_package_id_key')
    )
    with op.batch_alter_table('request_dependency', schema=None) as batch_op:
        batch_op.create_index('ix_request_dependency_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_request_dependency_replaced_dependency_id', ['replaced_dependency_id'], unique=False)
        batch_op.create_index('ix_request_dependency_package_id', ['package_id'], unique=False)
        batch_op.create_index('ix_request_dependency_dependency_id', ['dependency_id'], unique=False)

    # ### end Alembic commands ###
