"""Add RequestError table
Revision ID: 92f0d370ba4d
Revises: 418241dba06c
Create Date: 2022-07-15 16:42:12.752972
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92f0d370ba4d"
down_revision = "418241dba06c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_error",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.Enum("client", "server", name="requesterrororigin"), nullable=False),
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("occurred", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["request_id"], ["request.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("request_error", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_request_error_error_type"), ["error_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_error_occurred"), ["occurred"], unique=False)
        batch_op.create_index(batch_op.f("ix_request_error_origin"), ["origin"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_error", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_error_origin"))
        batch_op.drop_index(batch_op.f("ix_request_error_occurred"))
        batch_op.drop_index(batch_op.f("ix_request_error_error_type"))

    op.drop_table("request_error")
    # ### end Alembic commands ###
