"""Add environment variables types

Revision ID: cb6bdbe533cc
Revises: 615c19a1cee1
Create Date: 2020-06-22 14:56:53.584293

"""
from alembic import op
from sqlalchemy.engine.reflection import Inspector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb6bdbe533cc"
down_revision = "b46cf36806d7"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("environment_variable", schema=None) as batch_op:
        # Drop previous unique_constraint. Since the constraint was not originally added with a
        # name, the name could've been automatically generated by the database server. We must
        # inspect the table to find the correct name.
        inspector = Inspector.from_engine(batch_op.get_bind())
        unique_constraints = inspector.get_unique_constraints("environment_variable")
        old_unique_constraint = None
        for constraint in unique_constraints:
            if set(constraint["column_names"]) == {"name", "value"}:
                old_unique_constraint = constraint
                break
        if old_unique_constraint:
            batch_op.drop_constraint(old_unique_constraint["name"], type_="unique")

        # Make this nullable initially, so we can adjust the data first
        batch_op.add_column(sa.Column("kind", sa.String(), nullable=True))

    connection = op.get_bind()
    connection.execute("UPDATE environment_variable SET kind='path' WHERE kind IS NULL")

    with op.batch_alter_table("environment_variable", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_environmet_variable_name_value_kind", ["name", "value", "kind"]
        )
        batch_op.alter_column("kind", nullable=False)


def downgrade():
    with op.batch_alter_table("environment_variable", schema=None) as batch_op:
        batch_op.drop_constraint("uq_environmet_variable_name_value_kind", type_="unique")
        batch_op.drop_column("kind")
        batch_op.create_unique_constraint("uq_environmet_variable_name_value", ["name", "value"])
