FROM registry.fedoraproject.org/fedora:35
LABEL maintainer="Red Hat"

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    golang \
    gcc \
    git-core-2.32.0 \
    krb5-devel \
    libffi-devel \
    mercurial \
    npm \
    procps \
    python3-devel \
    python3-pip \
    python3-setuptools \
    strace \
    https://kojipkgs.fedoraproject.org//packages/golang/1.17/2.fc36/noarch/golang-src-1.17-2.fc36.noarch.rpm \
    https://kojipkgs.fedoraproject.org//packages/golang/1.17/2.fc36/x86_64/golang-1.17-2.fc36.x86_64.rpm \
    https://kojipkgs.fedoraproject.org//packages/golang/1.17/2.fc36/x86_64/golang-bin-1.17-2.fc36.x86_64.rpm \
    && dnf clean all

COPY . .

# All the requirements except pyarn should already be installed
RUN pip3 install -r requirements.txt --no-deps --no-cache-dir --require-hashes \
    && pip3 install . --no-deps --no-cache-dir

# Use the system CA bundle for the requests library
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
# Use the system CA bundle for native SSL calls from celery (python)
ENV SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt

# Set git user configuration for GitPython
ENV GIT_COMMITTER_NAME=cachito \
    GIT_COMMITTER_EMAIL=cachito@localhost \
    GIT_AUTHOR_NAME=cachito \
    GIT_AUTHOR_EMAIL=cachito@localhost

EXPOSE 8080
CMD ["celery", "-A", "cachito.workers.tasks", "worker", "--loglevel=info"]
