FROM fedora:29
LABEL maintainer="Factory 2.0"

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    golang \
    git-core \
    python3-celery \
    python3-requests \
    && dnf clean all
COPY . .
RUN pip3 install . --no-deps
EXPOSE 8080
CMD ["/bin/celery-3", "-A", "cachito.workers.tasks", "worker", "--loglevel=info"]
