FROM registry.fedoraproject.org/fedora:33
LABEL maintainer="Red Hat"

RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python3-pip
RUN pip3 install flower==0.9.7

COPY ./docker/flower-waits-for-cachito.sh /usr/local/bin/
