FROM registry.fedoraproject.org/fedora:35
LABEL maintainer="Red Hat"

RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    python3-pip \
    python3-setuptools \
    && dnf clean all \
    && pip3 install flower==0.9.7 --no-cache-dir

COPY ./docker/flower-waits-for-cachito.sh /usr/local/bin/
