FROM registry.fedoraproject.org/fedora:33
LABEL maintainer="Red Hat"

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    httpd \
    gcc \
    mod_auth_gssapi \
    mod_ssl \
    mod_wsgi \
    krb5-devel \
    python3-pip \
    python3-setuptools \
    python-devel \
    && dnf clean all
COPY . .
COPY ./docker/cachito-httpd.conf /etc/httpd/conf/httpd.conf

RUN pip3 install -r requirements.txt --no-deps --no-cache-dir --require-hashes
RUN pip3 install -r requirements-web.txt --no-deps --no-cache-dir --require-hashes
RUN pip3 install . --no-deps --no-cache-dir

# Use the system CA bundle for the requests library
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

# Disable gitpython check for the git executable, cachito-api doesn't use git
ENV GIT_PYTHON_REFRESH=quiet

EXPOSE 8080
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
